name: das-campaign-experiment
trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

jobs:
- job: 'CodeBuild'
  pool:
    name: 'DAS - Continuous Integration'
  workspace:
    clean: all 
  steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion
    inputs:
      updateAssemblyInfo: true

  - task: DotNetCoreCLI@2
    displayName: dot restore
    inputs:
      command: restore
      projects: 'src/**/*.csproj'
      noCache: true

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(buildConfiguration)  --no-restore'
      
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '**/*.UnitTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Function App '
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Experiment.Function/SFA.DAS.Experiment.Function.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore  --no-build'
    
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      pathtoPublish: "$(build.artifactstagingdirectory)/publish"